services:
  farejador:
    build: .
    image: python:3.12-slim
    container_name: div_bot_watchdog
    hostname: div_bot_watchdog
    restart: always
    volumes:
      - /opt/bot_div_watchdog:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"